from setuptools import setup, find_packages

setup(
    name="mofi",
    description="MOFI: Multi-Omics Fate Inference",
    author="Jiantao Shen, Rui Liu, Peijie Zhou",
    author_email="pjzhou@pku.edu.cn",
    url="https://github.com/jiantaoShen12/MOFI",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    install_requires=[
        "matplotlib",
        "numpy",
        "torch",
        "torchdiffeq",
        "torchsde",
        "scipy",
        "scikit-learn",
        "pot",
        "pyyaml",
        "tqdm",
        "seaborn",
        "pandas",
        "scanpy",
        "geomloss",
        "anndata",
        "h5py",
        "umap-learn",
        "plotly",
        "nbformat",
        "nbclient",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "Programming Language :: Python :: 3",
    ],
)
